name: Node.js Auto Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        # A directory to store and save the cache
        path: node_modules
        # An explicit key for restoring and saving the cache
        key: node_deps
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: unpack
      run: mkdir -p build/unpack && cd build/unpack && unzip ../*.zip
    - name: Upload
      uses: actions/upload-artifact@v2-preview
      with:
        name: h5ai-release
        path: ./build/unpack/*
